<#
.SYNOPSIS
Compares approved applications from an Excel file with applications
listed in a CSV file generated by another PowerShell script (without elevation).

.DESCRIPTION
This script reads a list of approved applications from an Excel file,
runs a separate PowerShell script to get application data, reads the
generated CSV file, compares the application lists, and adds a 'Status'
column to the application data indicating 'Approved' or 'UnApproved'.
The updated data is then saved to a new CSV file.

.NOTES
- Requires the ImportExcel PowerShell module to read Excel files.
  If not installed, run: Install-Module -Name ImportExcel -Scope CurrentUser
- Ensure the 'GetApps_and_hashes.ps1' script correctly generates the CSV file
  with the expected naming convention and includes an 'ApplicationName' column.
- This script does NOT require administrative privileges, but the
  'GetApps_and_hashes.ps1' script must also not require elevation.
#>

# Define file paths and directory
$ApprovedListPath = "c:\PySC\approved_Applications_list.xlsx"
$PowershellScriptPath = "C:\PySC\GetApps_and_hashes.ps1"
$OutputCsvDirectory = "C:\PySC\Apps"
$ComparisonResultsDirectory = "C:\PySC\Apps" # Directory to save comparison results

# Ensure the ImportExcel module is available
try {
    Import-Module -Name ImportExcel -ErrorAction Stop
} catch {
    Write-Host "ImportExcel module not found. Attempting to install..."
    try {
        Install-Module -Name ImportExcel -Scope CurrentUser -Force -ErrorAction Stop
        Import-Module -Name ImportExcel -ErrorAction Stop
        Write-Host "ImportExcel module installed and imported successfully."
    } catch {
        Write-Error "Failed to install and import ImportExcel module. Please install it manually: Install-Module -Name ImportExcel"
        exit 1 # Exit the script if the module cannot be imported.
    }
}

# 1. Read Approved Applications from Excel
try {
    $ApprovedApps = Import-Excel -Path $ApprovedListPath
    $ApprovedAppNames = $ApprovedApps.ApplicationName # Assuming 'ApplicationName' is the column name in the Excel file.
} catch {
    Write-Error "Error reading approved applications list: $_"
    exit 1
}

# Get the computer name
$ComputerName = $env:COMPUTERNAME

# 2. Run PowerShell script (without administrative privileges)
Write-Host "Running PowerShell script..."
try {
    # Directly invoke the script without Start-Process and -Verb RunAs
    # Ensure this script doesn't require admin privileges
    & $PowershellScriptPath -ErrorAction Stop
    Write-Host "PowerShell script executed successfully."
} catch {
    Write-Error "Error running PowerShell script: $_"
    exit 1
}

# 3. Read CSV file results of powershell script
# Construct the CSV file path dynamically using the actual computer name and the correct date format
$TodayDateYYMMDD = Get-Date -Format "yyMMdd"
$ApplicationsCsvFileName = "${ComputerName}_Applications_${TodayDateYYMMDD}.csv"
$ApplicationsCsvPath = Join-Path -Path $OutputCsvDirectory -ChildPath $ApplicationsCsvFileName

try {
    $ApplicationsData = Import-Csv -Path $ApplicationsCsvPath -ErrorAction Stop
    Write-Host "Applications data CSV file read successfully."
} catch {
    Write-Error "Error reading applications data CSV file: $_"
    exit 1
}

# 4. Compare applicationName and append 'Status' column
$ComparisonResults = $ApplicationsData | ForEach-Object {
    $AppData = $_
    # Check if the application name from the CSV is in the list of approved application names
    if ($ApprovedAppNames -contains $AppData.ApplicationName) { # Assuming 'ApplicationName' is the column name in the CSV
        $AppData | Add-Member -MemberType NoteProperty -Name "Status" -Value "Approved" -Force
    } else {
        $AppData | Add-Member -MemberType NoteProperty -Name "Status" -Value "UnApproved" -Force
    }
    $AppData
}

# Save the updated data to a new CSV file
$TodayDateYYYYMMDD = Get-Date -Format "yyyyMMdd"
$OutputComparisonCsvFileName = "Comparison_Results_${ComputerName}_${TodayDateYYYYMMDD}.csv"
$OutputComparisonCsvPath = Join-Path -Path $ComparisonResultsDirectory -ChildPath $OutputComparisonCsvFileName

try {
    $ComparisonResults | Export-Csv -Path $OutputComparisonCsvPath -NoTypeInformation -ErrorAction Stop
    Write-Host "Comparison complete. Results saved to: $OutputComparisonCsvPath"
} catch {
    Write-Error "Error saving comparison results: $_"
    exit 1
}
